version: "3.9"

services:
  mysql-db:
    image: mysql:8.0.33
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  backend:
    image: biplob141/todo-backend:latest
    container_name: todo-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "rootpassword"
      DB_NAME: todo_db
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      mysql-db:
        condition: service_healthy
    # Healthcheck disabled temporarily or use a simpler check
    healthcheck:
      test: ["CMD-SHELL", "echo 'Health check passed' || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: biplob141/todo-frontend:latest
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started  # Changed from service_healthy
    environment:
      - REACT_APP_API_URL=http://backend:5000
    # Disable healthcheck for frontend or use a simple check
    healthcheck:
      disable: true  # Disable healthcheck for frontend

volumes:
  mysql-data: